CRUD2/CRUD2/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("stu/",views.stu),
    path("show/",views.show),
    path("edit/<int:rollno>",views.edit),
    path("update/<int:rollno>",views.update),
    path("delete/<int:rollno>",views.delete),
]

CRUD2/app/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    rollno = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50)
    def __str__(self):
        return self.name

CRUD2/app/forms.py
from django import forms
from .models import Student
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','subject']

CRUD2/app/views.py
from django.shortcuts import render, redirect
from .forms import StudentForm
from .models import Student
# Create your views here.
def home(request):
    return render(request, 'home.html')

def stu(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = StudentForm()
    return render(request, 'index.html',{'form':form})

def show(request):
    students = Student.objects.all()
    return render(request, 'show.html',{'students':students})

def edit(request, rollno):
    student = Student.objects.get(rollno=rollno)
    return render(request, 'edit.html',{'student':student})

def update(request, rollno):
    student = Student.objects.get(rollno=rollno)
    form = StudentForm(request.POST,instance=student)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html',{'student':student})

def delete(request, rollno):
    student = Student.objects.get(rollno=rollno)
    student.delete()
    return redirect('/show')

CRUD2/app/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit</title>
  <link rel="stylesheet" href="{% static 'style.css' %}"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <form method="POST" class="post-form" action = '/update/{{student.rollno}}'>
    {% csrf_token %}
    <div class="container">
      <br>
      <h2>Student Information </h2><br>
      <div class="from-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Update Details</h3>
        </div>
      </div>

      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Student Name : </label>
        <div class="col-sm-4">
          <input type="text" name="name" id="id_name" required maxlength="20" value="{{ student.name }}"/>
        </div>
      </div>


      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Student Subject : </label>
        <div class="col-sm-4">
          <input type="text" name="subject" id="id_subject" required maxlength="254" value="{{ student.subject }}"/>
        </div>
      </div>

      <div class="form-group row">  
        <label class="col-sm-3 col-form-label"></label>  
        <div class="col-sm-4">  
          <button type="submit" class="btn btn-success">Update</button>  
          <button type="reset" class="btn btn-dark">Reset</button>
        </div>  
      </div>

    </div>
  </form>
</body>
</html>

CRUD2/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Information App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <form  method="post" class="post-form">
        {% csrf_token %}
            <div class="form-group row">
                <label class="col-sm-4 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Student Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Student Name : </label>
                <div class="col-sm-4">{{ form.name }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Student Subject : </label>
                <div class="col-sm-4">{{ form.subject }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

CRUD2/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Information App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <table class="table table-striped table-striped table-sm table-dark">
        <thead class="thead-dark">
            <tr>
                <th>Student Rollno</th>
                <th>Student Name</th>
                <th>Student Subject</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.rollno }}</td>
                    <td>{{ student.name }}</td>
                    <td>{{ student.subject }}</td>
                    <td>
                        <a href="/update/{{ student.rollno }}" class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil">Edit</span>
                        </a>&nbsp;&nbsp;
                        <a href="/delete/{{ student.rollno }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <center><a href="/stu" class="btn btn-primary">Add New Record</a></center>
</body>
</html>